# Generated by Django 5.2.17 on 2026-10-03 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task_assigned', 'Task assigned to me'), ('task_status', 'Task status changed'), ('task_comment', 'New comment on my task'), ('task_deadline', 'Task deadline approaching'), ('mention', 'Mentioned in chat'), ('direct_message', 'New direct message'), ('follow_up', 'Client follow-up due'), ('approval_request', 'Approval requested'), ('approval_result', 'My request approved/rejected'), ('announcement', 'New announcement'), ('booking', 'Booking updates'), ('visit', 'Field visit updates'), ('system', 'System and security')], default='system', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, help_text='Frontend route to open, e.g. /tasks/12', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('task_assigned', 'Task assigned to me'), ('task_status', 'Task status changed'), ('task_comment', 'New comment on my task'), ('task_deadline', 'Task deadline approaching'), ('mention', 'Mentioned in chat'), ('direct_message', 'New direct message'), ('follow_up', 'Client follow-up due'), ('approval_request', 'Approval requested'), ('approval_result', 'My request approved/rejected'), ('announcement', 'New announcement'), ('booking', 'Booking updates'), ('visit', 'Field visit updates'), ('system', 'System and security')], max_length=30)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'type'), name='unique_notification_pref')],
            },
        ),
    ]
