# Generated by Django 5.2.17 on 2026-10-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'verbose_name': 'notification preference', 'verbose_name_plural': 'notification preferences'},
        ),
        migrations.AddField(
            model_name='notification',
            name='message_key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='params',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
