# Generated by Django 5.2.17 on 2026-10-03 15:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(default='Our Office', max_length=150)),
                ('currency', models.CharField(default='PKR', max_length=3)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD MMM YYYY', 'DD MMM YYYY')], default='DD/MM/YYYY', max_length=20)),
                ('timezone', models.CharField(default='Asia/Karachi', max_length=64)),
                ('week_start', models.PositiveSmallIntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (6, 'Saturday')], default=1)),
                ('default_language', models.CharField(choices=[('en', 'English'), ('ur', 'Urdu')], default='en', max_length=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'organization settings',
                'verbose_name_plural': 'organization settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Logged in'), ('login_failed', 'Failed login'), ('logout', 'Logged out'), ('security', 'Security change'), ('other', 'Other')], max_length=20)),
                ('object_id', models.CharField(blank=True, max_length=64)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_entries', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor', '-timestamp'], name='core_auditl_actor_i_cba5aa_idx'), models.Index(fields=['content_type', 'object_id'], name='core_auditl_content_fec0c4_idx')],
            },
        ),
    ]
