# Generated by Django 5.2.17 on 2026-10-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'audit entry', 'verbose_name_plural': 'audit entries'},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Signed in'), ('login_failed', 'Failed sign-in'), ('logout', 'Signed out'), ('security', 'Security change'), ('other', 'Other')], max_length=20),
        ),
    ]
