# Generated by Django 5.2.17 on 2026-10-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_heartbeat_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='staff_can_export_contacts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='staff_can_import_contacts',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('login', 'Signed in'), ('login_failed', 'Failed sign-in'), ('logout', 'Signed out'), ('security', 'Security change'), ('import', 'Imported'), ('export', 'Exported'), ('other', 'Other')], max_length=20),
        ),
    ]
