# Generated by Django 5.2.17 on 2026-10-09 12:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Existing contacts: best-known status date, and an initial history row at creation."""
    Contact = apps.get_model("contacts", "Contact")
    Change = apps.get_model("contacts", "ContactStatusChange")
    rows = []
    for c in Contact.objects.all().iterator():
        Contact.objects.filter(pk=c.pk).update(status_changed_at=c.updated_at)
        rows.append(Change(contact_id=c.pk, from_status="", to_status=c.status, changed_by_id=c.created_by_id, changed_at=c.created_at))
    Change.objects.bulk_create(rows, batch_size=500)



class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_tag_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status_changed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ContactStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_discussion', 'In discussion'), ('won', 'Won'), ('lost', 'Lost')], max_length=20)),
                ('to_status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('in_discussion', 'In discussion'), ('won', 'Won'), ('lost', 'Lost')], db_index=True, max_length=20)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('changed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_changes', to='contacts.contact')),
            ],
            options={
                'verbose_name': 'status change',
                'verbose_name_plural': 'status changes',
                'ordering': ['-changed_at', '-id'],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
