# Generated by Django 5.2.17 on 2026-10-10 15:01

from django.db import migrations, models


def fill_phone_digits(apps, schema_editor):
    from apps.core.phones import normalize_phone

    Model = apps.get_model("contacts", "Company")
    for obj in Model.objects.exclude(phone="").only("pk", "phone"):
        Model.objects.filter(pk=obj.pk).update(phone_digits=normalize_phone(obj.phone))


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contactimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='phone_digits',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=30),
        ),
        migrations.RunPython(fill_phone_digits, migrations.RunPython.noop),
    ]
