# Generated by Django 5.2.17 on 2026-10-05 16:11

import apps.core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_department_options_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='totp_secret',
            field=apps.core.fields.EncryptedTextField(blank=True),
        ),
    ]
